version: '3.3'

services:
  mysql:
    image: mysql:5.7
    container_name: plask-mysql
    restart: always
    ports:
      - 11510:3306
    networks:
      - dev-network      
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: plask
      MYSQL_USER: plask
      MYSQL_PASSWORD: plask
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - plask-mysql:/var/lib/mysql

volumes:
  plask-mysql:
  
networks:
  dev-network:
    driver: bridge

